# Generated by Django 3.0.3 on 2020-05-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Causa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_causa', models.CharField(max_length=50, verbose_name='Número de causa')),
                ('expediente', models.CharField(max_length=50, verbose_name='Expediente')),
                ('caratula', models.CharField(max_length=50, verbose_name='Carátula de causa')),
                ('estado_causa', models.CharField(choices=[('curso', 'En curso'), ('elev', 'Elevada'), ('tram', 'En espera')], default='En espera', max_length=10, verbose_name='Estado de causa')),
                ('fecha', models.DateTimeField(verbose_name='Fecha de Entrada')),
                ('fecha_elev2', models.CharField(blank=True, max_length=15, null=True, verbose_name='Fecha de elevación (DD/MM/AA)')),
                ('juzgado', models.CharField(max_length=50, verbose_name='Juzgado interviniente')),
                ('resp_juzgado', models.CharField(max_length=50, verbose_name='Responsable de juzgado')),
                ('tel_juzgado', models.CharField(max_length=12, verbose_name='Teléfono de juzgado')),
                ('secretaria', models.CharField(max_length=50, verbose_name='Número de secretaría')),
                ('resp_secretaria', models.CharField(max_length=50, verbose_name='Responsable de secretaría')),
                ('resp_PNA', models.CharField(max_length=50, verbose_name='Personal de PNA asignado')),
                ('observ2', models.TextField(default='', max_length=400, verbose_name='Observaciones')),
            ],
        ),
        migrations.CreateModel(
            name='Numeradore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_doc', models.CharField(choices=[('oficio', 'Oficio'), ('memorandum', 'Memorándum'), ('acta', 'Acta'), ('vista', 'Vista'), ('dispo', 'Disposición'), ('recibo', 'Recibo'), ('acta_tar', 'Acta de tarea')], default='Oficio', max_length=20, verbose_name='Tipo de documento')),
                ('clasif_seg', models.CharField(choices=[('public', 'Público'), ('confi', 'Confidencial'), ('reser', 'Reservado'), ('secret', 'Secreto')], default='Público', max_length=20, verbose_name='Clasificación de seguridad')),
                ('num_oficio', models.IntegerField(verbose_name='Número de oficio')),
                ('fecha_doc', models.DateField(verbose_name='Fecha')),
                ('referencia', models.CharField(max_length=100, verbose_name='Referencia')),
            ],
        ),
    ]
