# Generated by Django 3.0.3 on 2020-05-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_BBDD', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='causa',
            name='observ2',
            field=models.TextField(default='', max_length=400, verbose_name='Observaciones'),
        ),
    ]
