# Generated by Django 3.0.3 on 2020-05-19 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_BBDD', '0002_causa_observ2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='causa',
            name='observ',
        ),
    ]
