# Generated by Django 3.0.3 on 2020-05-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_BBDD', '0003_remove_causa_observ'),
    ]

    operations = [
        migrations.AddField(
            model_name='causa',
            name='fecha_elev2',
            field=models.CharField(default='', max_length=15, verbose_name='Fecha de elevación (DD/MM/AA)'),
            preserve_default=False,
        ),
    ]
