# Generated by Django 3.0.3 on 2020-05-19 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_BBDD', '0004_causa_fecha_elev2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='causa',
            name='fecha_elev',
        ),
    ]
